import localFont from 'next/font/local'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer';
import "./globals.css";

const IranSan = localFont({
  src:'./fonts/IRANSansWeb.ttf',
  variable: '--font-IranSan',
})

const IranSanBold = localFont({
  src:'./fonts/IRANSansWeb_Bold.ttf',
  variable: '--font-IranSanBold',
})

const IranSanLight = localFont({
  src:'./fonts/IRANSansWeb_Light.ttf',
  variable: '--font-IranSanLight',
})

export const metadata = {
  title: "Iran Carpet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className='font-IranSan'>
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
